repos:
- repo: local
  hooks:
  - id: changelogs-rst
    name: changelogs must be rst
    entry: changelog filenames must end in .rst
    language: fail
    files: 'changelog/.*(?<!\.rst)$'

  - id: pylint
    name: pylint
    entry: yapf -vv --style=google -i
    language: system
    types: [python]   